### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jjrv** [jjrv/systema#1]
- [ ] Detect, transpile and re-inject `<script type="application/systema">`
- [ ] Importing paths like `require('..')` should look for a `package.json` file.
- [ ] Avoid looking for `node_modules` directories in CDNs.
- [ ] Conditional compilation of `if` blocks conditioned on `process.env.NODE_ENV`.
- [x] Distribute a PostCSS bundle and use it for CSS files.
- [ ] Cache transpiled code in `localStorage` / `sessionStorage` / local file system.
- [x] Request correct package versions from CDNs based on package config and `package-lock.json`.
- [x] Allow bundling only external dependencies for development.
- [x] Easier way to save a bundle from browsers.
- [x] Remove clever fake inheritance from plugins.
- [x] Source maps.

**Comment by ISNIT0** [comment]
Could possibly cache dependencies using a service worker?

**Comment by jjrv** [comment]
That's definitely possible. It's the only reliable way to make the HTML page and loader itself accessible offline, even if everything else could go in `localStorage`. For the main app and its dependencies we get the same level of control even without service workers, because all imports go through the loader.

Another benefit of service workers is that an app might wish to call `localStorage.clear()` to remove its own temporary data, and the side effect of nuking the loader cache is inconvenient.

I'd still keep it an optional extra, because an app might need its own service worker for other purposes and making it support the loader might be a burden.

**Comment by jjrv** [comment]
[test.tar.gz](https://github.com/jjrv/systema/files/3144791/test.tar.gz)
